services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - nodemodules:/app/node_modules
      - next:/app/.next
      - .:/app
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=maqraa
    volumes:
      - db-data:/var/lib/posgresql/data
  adminer:
    image: adminer:4.8.1-standalone
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_PLUGINS=tables-filter edit-foreign

volumes:
  db-data:
  nodemodules:
  next:
